dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
addons:
  sonarcloud:
    organization: "cjscommonplatform"
    branches:
      - experimental
    token:
      secure: "7sS5OX7+3z8J140i+ioySobYRz02IDQ6w6NoPn9RzRg+i4ewPTE4Kd9BD+Lk8hjFDA+5FQeUm/lZl3gsPXktSDvas7XittgrXYaOOeiz30COe58whIqVAefow5zFAHR4R3jortGuOb77Yq9HdDdbVKkBW414cIwGJme751TnA/mq8XxCFAR9jlrGkL86nwggLz1DSqxZUy/p001R9AeSJFNCejxhaTcBvmyoKCjA2IeSE1mJQAUdeFDRuSfUAQIIp3Kpf5uwELSp4SgjXObCj6/+g7Zd9ofQQ5hS5UXlF/NzXM1wiQ2uObzknlOfLZZ9szivHHvm5rYbFH058e0Gwc5oohchWJ0kknOmHJqopjuHnSS2mNUxAGB6gZRZnUkWJ9dySzv1JrN9xln/PlVcqd4dx1L6lRbHp8IMMSohsOykxJM6SZ4ipPFfJIxv5LSwFfD7kkE60nF0GzVZNDFiX7OUkOefRJJ+/fV15UrdUnmYdPeOBPYxsbS+bkdIUNJQM7/BcR+A0NZ1JNADhrbcTvTbe7axoNulcr/csgDcuRMXvau7iGn86Z3ONaasApDVTlrRnXJagBzGWAdAKBifyPWd7W9KbPAmppJ3Ib9ML75jk7M+paGWyXIfgGH0ai4UZaSCFDLkEBMwMku37W1KtmHQUBB9z7EPNKMXo1o7jec="
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
install: "${PWD}/target/travis-settings/java/install.sh -DexcludeGroupIds=uk.gov.justice.services"
script: "${PWD}/target/travis-settings/java/script-install.sh coveralls:report sonar:sonar"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
notifications:
  slack:
  - secure: bZxPHt9OgOy6L4whNAnNi9OfGu1+enEvHahvRIn+hPEyHS0WlDxDZFw6cjxW170EY42H9hhCd3tuBhAytmiKf3d4tOIG3RNFZNi/btywutKKE2/qJz+qxzs22upmbvFSpbVhUGoOJr0JLPSd8hFJ1rwYiBCAOLVzpm+TSmVoYiUfFFhkpzP17xtG9aJHOI2QSvNlHVIR9J2VDb+LZ3WBvSJVAue+Qk18QB5/bqZ33Jeg5ayw09aoLQfR2+NuND/usk9qZ+Mt4j97YSpVzBR/FQTjvMzXngeFr7/Fl0U50DcKiwBjlev87nAilE3eZTSkPntzsmeq9XV0VjMG7dyDvyotHZb62c9gu/G+KefRELnruxSfz6u4BWKr/+LkV1jUalPeGQh5MRmZkKfit3QCbjLMJkS9MORhIpWg1oDzcRWJwXg7oUNttMj/1/j1evGL26rxdUVKJmLVUNYrlU1Sh/08cmCnNfSyqT5clVmsZnwQuHbP6qJsS6ReL3URHoRmwm2aR9opl1dv3GJ1REYH6akcm/NiOB20BtBetUkDNGAUb17xtnwM2WpWkpg7fstI8Vf+MFMJc5Ksti6aWBRbADSnaF2sIqMFGOwrT54TQB310n/Lf2tcWZv2V84y18cpMJCXrWeKtbVxIdJSnlLgbNloBBx1q/KUn3F7SckDHUw=
env:
  global:
  - secure: tPRHWEiDO4fhDRfLFOD+IdzucVy6efowGfVYEUO+PXUaxz5wEERU66Vk5aJnAwZuf8a/dBkGLyz2PUANfuIMy9la2QnKofl8FvLLXGJKOyvtnwsDPSS/3pDZPEUzMvnW9QiwGWfylrfSgO9Lx+ACjLqOCQk2WBuQnF4GFgT8pgIUQtg/nXOzUmUp4Z82GQDOFJL9PgCtSey2wTSd+Y80ge6aEMid0MTwAVHogtutCbEVsPSaxXS9fVKmBHbJ4wmbVzojpmWLPOhJ+JzBfgAL3Ct7Z5lUJGpSiY87ngDmOeHDCyJMng4wCBKhTTz+7B6AMHLMn6rO0ZOWkyxj3dwZ7x6nr+IG/cXNf0DQSiYYU3lw4r+KVlqXDI4N0MQ9Udmbj/oxL71oHFCxpOlLXja3h0tHPgC1SpSpEwxZqtZJ3Q7JqoaSg7C3CIFNN+xDJr5gYw6z3VHKM0aMCl3l0EzElgs+kalqI3FiYwT34vav/+bGtqXhl1iX1YJ/msrNZV/aRkvEJUeND1mS1Y4oZNwTEmDw/HRd3b9lgErMASoB9UeCH3A+05NKwuvxLu72XsGNDgxYKNvHkcYuaYnt6bCO8qzF1CuDZ2KDPyBKw3Qh47BU/cRWw19AqFrJ1PziEkCFqa00s0rnC1yuqx5It0+fYBURFFDmhrFN0MQJG50JTkM=
  - secure: Qu+RFJ97r2IanKPUb7Eo2HD9HEemTwnMU3ZsUpZMhDy25VbJ+sL9JUUgpDVACOt2Fm47xoy6gCGJI0qQ5M+IupLsHdm8ZAhtNT2yaVlT5HlI6XPnkVRSnWk4AqsM3OHC4Xu4mj/px5ZZHJtnLG3yWnhQXBCgDNskP9EWwUdmg7cJGCdIJ4j6uMt5MV1Hy08kjnXgWCNZtSdUYxb62fqXI6LOaGooTZq9lOSsgqh2CbDMscgFx1ZVPQ5i/CKS9kF8F4kswgQWajGnRo8aoQxCxQHxBX1k4ieKtza+36N1wcqGRD1tb0n/P8JahS0nsHys5iGxiryybW7vGArrRl/fSoMKgudADJX4hsKlLedkVZt5eORAYOMgopDvDfaDiqAZh6N0p2os67PoJmN0Op0TgJdrZtUB9sFKGnmhH0j3FJ1NV4aA+vdMX/sLtkFcihGeOW9Fe8roHaTXnY34PHi/ZfAp/3AbDtZDPe15kjm4Y8aEYXX1IFh3BO4lbGz5OHbERJ6h9DgWUB0xqwPTS+3uJ/J5eWRmgkWbHDwZvawTngQ383PbL/654pqKUnAsypj0vPks2873spwU1Lod0ZUTLvsa5WjB2sxU49/uYgcEyPni3eycTxzjP0c5W8gze0rIOgfrRIjAV1RUGjgdFqsuXnhW9q6bNOJL0aLLNfsli18=
