dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
install: "${PWD}/target/travis-settings/java/install.sh -DexcludeGroupIds=uk.gov.justice.services"
script: "${PWD}/target/travis-settings/java/script.sh coveralls:report"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
notifications:
  slack:
    - secure: "bZxPHt9OgOy6L4whNAnNi9OfGu1+enEvHahvRIn+hPEyHS0WlDxDZFw6cjxW170EY42H9hhCd3tuBhAytmiKf3d4tOIG3RNFZNi/btywutKKE2/qJz+qxzs22upmbvFSpbVhUGoOJr0JLPSd8hFJ1rwYiBCAOLVzpm+TSmVoYiUfFFhkpzP17xtG9aJHOI2QSvNlHVIR9J2VDb+LZ3WBvSJVAue+Qk18QB5/bqZ33Jeg5ayw09aoLQfR2+NuND/usk9qZ+Mt4j97YSpVzBR/FQTjvMzXngeFr7/Fl0U50DcKiwBjlev87nAilE3eZTSkPntzsmeq9XV0VjMG7dyDvyotHZb62c9gu/G+KefRELnruxSfz6u4BWKr/+LkV1jUalPeGQh5MRmZkKfit3QCbjLMJkS9MORhIpWg1oDzcRWJwXg7oUNttMj/1/j1evGL26rxdUVKJmLVUNYrlU1Sh/08cmCnNfSyqT5clVmsZnwQuHbP6qJsS6ReL3URHoRmwm2aR9opl1dv3GJ1REYH6akcm/NiOB20BtBetUkDNGAUb17xtnwM2WpWkpg7fstI8Vf+MFMJc5Ksti6aWBRbADSnaF2sIqMFGOwrT54TQB310n/Lf2tcWZv2V84y18cpMJCXrWeKtbVxIdJSnlLgbNloBBx1q/KUn3F7SckDHUw="
